steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-C', './simple-http-response-ts/deploy.sh']

- name: gcr.io/cloud-builders/gcloud
  args: [
      'beta',
      'functions',
      'deploy','${_NAME}',
      '--source=./dist',
      '--entry-point=upload',
      '--project=${PROJECT_ID}',
  ]